from classifiers.apple_desease_classifier import get_apple_classifier, AppleDeseaseClassifier
from classifiers.pepper_desease_classifier import get_pepper_classifier, PepperDeseaseClassifier
from classifiers.tomato_desease_classifier import get_tomato_classifier, TomatoDeseaseClassifier
from classifiers.corn_desease_classifier import get_corn_classifier, CornDeseaseClassifier
from classifiers.potato_desease_classifier import get_potato_classifier, PotatoDeseaseClassifier
